   version: '3.8'
   services:
     app:
       image: rizkifajar456/laravel-library-api:app-latest
       build:
         context: .
         dockerfile: Dockerfile
       volumes:
         - .:/var/www/html
       depends_on:
         db:
           condition: service_healthy
         redis:
           condition: service_started
       environment:
         DB_CONNECTION: pgsql
         DB_HOST: db
         DB_PORT: 5432
         DB_DATABASE: library_db
         DB_USERNAME: postgres
         DB_PASSWORD: postgres
         REDIS_HOST: redis
         REDIS_PORT: 6379
     webserver:
       image: rizkifajar456/laravel-library-api:nginx-latest
       ports:
         - "8000:80"
       volumes: 
         - .:/var/www/html
         - ./nginx.conf:/etc/nginx/conf.d/default.conf
       depends_on:
         - app

     db:
       image: rizkifajar456/laravel-library-api:postgres-latest
       environment:
         POSTGRES_DB: library_db
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
       volumes:
         - postgres_data:/var/lib/postgresql/data
       ports:
         - "5432:5432"
       healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 5s
         timeout: 5s
         retries: 5

     redis:
       image: rizkifajar456/laravel-library-api:redis-latest
       ports:
         - "6379:6379"

   volumes:
     postgres_data: